Update resources that already exist instead of failing. Fixes #3189
This patch updates resources that already exist when running helm install or helm upgrade.

Previously, Helm would fail with an error:

```
Error: release jdeploy5 failed: services "deploytest" already exists
```

After this patch, the resources will be updated instead of failing the release.

Signed-off-by: Justin Barrick <jbarrick@cloudflare.com>