fix: error when more than one post-renderer is specified
We now make sure the post-renderer flag can be passed at most once instead of silently taking the last one passed.

Example:

```bash
$ helm template test ...  --post-renderer=true --post-renderer=cat
Error: invalid argument "cat" for "--post-renderer" flag: cannot set post-renderer more than once, given: cat, previous: true
```

Signed-off-by: Yarden Shoham <git@yardenshoham.com>