[dev-v3] bump golang.org/x/text@v0.39.0 for GO-2026-5970
Related to https://github.com/helm/helm/pull/32310
however cherry-picking is not working well here
and for this patch release, this was fixed in v0.39.0 so not bumping to v0.40.0 here

fixed with:

```
go get golang.org/x/text@v0.39.0
go mod tidy
```

example actions fail:

```
  Vulnerability #2: GO-2026-5970
      Infinite loop on invalid input in golang.org/x/text
    More info: https://pkg.go.dev/vuln/GO-2026-5970
    Module: golang.org/x/text
      Found in: golang.org/x/text@v0.38.0
      Fixed in: golang.org/x/text@v0.39.0
      Example traces found:
  Error:       #1: pkg/repo/repotest/server.go:148:2: repotest.OCIServer.Run calls registry.Registry.ListenAndServe, which eventually calls norm.Form.Bytes
  Error:       #2: pkg/repo/repotest/server.go:148:2: repotest.OCIServer.Run calls registry.Registry.ListenAndServe, which eventually calls norm.Form.IsNormalString
  Error:       #3: cmd/helm/docs.go:89:61: helm.run calls cases.Caser.String, which eventually calls norm.Form.Properties
  Error:       #4: pkg/repo/repotest/server.go:148:2: repotest.OCIServer.Run calls registry.Registry.ListenAndServe, which eventually calls norm.Form.QuickSpan
  Error:       #5: pkg/repo/repotest/server.go:148:2: repotest.OCIServer.Run calls registry.Registry.ListenAndServe, which eventually calls norm.Form.String
```

Signed-off-by: Scott Rigby <scott@r6by.com>