feat(kube): add schema validation
Adds validation against the swagger schema.

Example error:
Error: release telling-wildebeest failed: error validating "": error
validating data: expected type int, for field
spec.template.spec.containers[0].ports[0].containerPort, got string

Current error:
unable to decode "": [pos 177]: json: expect char '"' but got char 'n'"'