Fix deprecation warning
Error reported in CI https://github.com/helm/helm/actions/runs/17623700524/job/50075176523?pr=31231

```
Error: cmd/helm/root.go:165:2: SA1019: flags.ParseErrorsWhitelist is deprecated: use [FlagSet.ParseErrorsAllowlist] instead. This field will be removed in a future release. (staticcheck)
```

Close: #31231
Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>
(cherry picked from commit 9a366b447452e78b092b1a5267d7efc9bbe74f11)