[dev-v3 backport] deps: bump google.golang.org/grpc@v1.82.1 for GO-2026-6061
backport of https://github.com/helm/helm/pull/32450

updated with:

```
go get google.golang.org/grpc@v1.82.1
go mod tidy
```

example actions failure:
https://github.com/helm/helm/actions/runs/31733009013/job/94557780520

```
  Vulnerability #1: GO-2026-6061
      Vulnerabilities in the xDS RBAC authorization engine and the HTTP/2
      transport server implementation in google.golang.org/grpc
    More info: https://pkg.go.dev/vuln/GO-2026-6061
    Module: google.golang.org/grpc
      Found in: google.golang.org/grpc@v1.80.0
      Fixed in: google.golang.org/grpc@v1.82.1
      Example traces found:
  Error:       #1: pkg/repo/repotest/server.go:128:32: repotest.NewOCIServer calls registry.NewRegistry, which eventually calls transport.ClientStream.Close
  Error:       #2: pkg/repo/repotest/server.go:128:32: repotest.NewOCIServer calls registry.NewRegistry, which eventually calls transport.ClientStream.Header
  Error:       #3: pkg/repo/repotest/server.go:128:32: repotest.NewOCIServer calls registry.NewRegistry, which eventually calls transport.ClientStream.Read
  Error:       #4: pkg/repo/repotest/server.go:128:32: repotest.NewOCIServer calls registry.NewRegistry, which eventually calls transport.ClientStream.RecvCompress
  Error:       #5: pkg/repo/repotest/server.go:128:32: repotest.NewOCIServer calls registry.NewRegistry, which eventually calls transport.ClientStream.TrailersOnly
  Error:       #6: pkg/repo/repotest/server.go:128:32: repotest.NewOCIServer calls registry.NewRegistry, which eventually calls transport.ClientStream.Write
  Error:       #7: pkg/action/lazyclient.go:49:17: action.lazyClient.init calls sync.Once.Do, which eventually calls transport.NewHTTP2Client
  Error:       #8: pkg/repo/repotest/server.go:128:32: repotest.NewOCIServer calls registry.NewRegistry, which eventually calls transport.Stream.ReadMessageHeader
  Error:       #9: pkg/action/lazyclient.go:49:17: action.lazyClient.init calls sync.Once.Do, which eventually calls transport.http2Client.Close
  Error:       #10: pkg/action/lazyclient.go:49:17: action.lazyClient.init calls sync.Once.Do, which eventually calls transport.http2Client.GracefulClose
  Error:       #11: pkg/repo/repotest/server.go:128:32: repotest.NewOCIServer calls registry.NewRegistry, which eventually calls transport.http2Client.NewStream
```

Signed-off-by: Scott Rigby <scott@r6by.com>
(cherry picked from commit 79062a64acb4e0cc062ac61c3c7e33177f326ff1)